resolver: lts-11.16

packages:
- '.'
- location:
    git: git@github.com:packetloop/datadog.git
    commit: d7c5b246e02677596ca03bf699c490d0c4470066
  extra-dep: true
- location:
    git: git@github.com:packetloop/hs-arbor-logger.git
    commit: 85f56acbd43625793b09aa5281c6224a7cca7d76
  extra-dep: true

- location:
    git: git@github.com:snoyberg/http-client.git
    commit: c733664b6466fc892775e0b9a97525be2570f286
    subdirs:
      - http-client
  extra-dep: true

- location:
    git: git@github.com:brendanhay/amazonka.git
    commit: 248f7b2a7248222cc21cef6194cd1872ba99ac5d
    subdirs:
      - amazonka
      - amazonka-s3
  extra-dep: true

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
  - avro-0.3.2.0
  - hedgehog-0.5.3
  - hw-hedgehog-0.1.0.1
  - hw-hspec-hedgehog-0.1.0.1
  - hw-kafka-avro-2.1.0
  - hw-kafka-client-2.5.0
  - hw-kafka-conduit-2.5.0
  - pure-zlib-0.6
  - hw-conduit-0.2.0.3

# Override default flag values for local packages and extra-deps
flags: {}

extra-package-dbs: []

# Added docker build configuration
# but disabled docker build by default.
# "stack --docker build" will use this configuration.
docker:
  enable: false
  repo: "fpco/stack-build:latest"
  auto-pull: true

